/* Generated by wayland-scanner 1.24.0 */

/*
 * Copyright © 2017 Drew DeVault
 *
 * Permission to use, copy, modify, distribute, and sell this
 * software and its documentation for any purpose is hereby granted
 * without fee, provided that the above copyright notice appear in
 * all copies and that both that copyright notice and this permission
 * notice appear in supporting documentation, and that the name of
 * the copyright holders not be used in advertising or publicity
 * pertaining to distribution of the software without specific,
 * written prior permission.  The copyright holders make no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied
 * warranty.
 *
 * THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
 * SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
 * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
 * THIS SOFTWARE.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_output_interface;
extern const struct wl_interface wl_surface_interface;
extern const struct wl_interface xdg_popup_interface;
extern const struct wl_interface zwlr_layer_surface_v1_interface;

static const struct wl_interface *wlr_layer_shell_unstable_v1_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	&zwlr_layer_surface_v1_interface,
	&wl_surface_interface,
	&wl_output_interface,
	NULL,
	NULL,
	&xdg_popup_interface,
};

static const struct wl_message zwlr_layer_shell_v1_requests[] = {
	{ .name="get_layer_surface", .signature="no?ous", .types=wlr_layer_shell_unstable_v1_types + 4 },
	{ .name="destroy", .signature="3", .types=wlr_layer_shell_unstable_v1_types + 0 },
};

const struct wl_interface zwlr_layer_shell_v1_interface = {
	.name="zwlr_layer_shell_v1", .version=4,
	.method_count=2, .methods=zwlr_layer_shell_v1_requests,
	.event_count=0, .events=NULL,
};

static const struct wl_message zwlr_layer_surface_v1_requests[] = {
	{ .name="set_size", .signature="uu", .types=wlr_layer_shell_unstable_v1_types + 0 },
	{ .name="set_anchor", .signature="u", .types=wlr_layer_shell_unstable_v1_types + 0 },
	{ .name="set_exclusive_zone", .signature="i", .types=wlr_layer_shell_unstable_v1_types + 0 },
	{ .name="set_margin", .signature="iiii", .types=wlr_layer_shell_unstable_v1_types + 0 },
	{ .name="set_keyboard_interactivity", .signature="u", .types=wlr_layer_shell_unstable_v1_types + 0 },
	{ .name="get_popup", .signature="o", .types=wlr_layer_shell_unstable_v1_types + 9 },
	{ .name="ack_configure", .signature="u", .types=wlr_layer_shell_unstable_v1_types + 0 },
	{ .name="destroy", .signature="", .types=wlr_layer_shell_unstable_v1_types + 0 },
	{ .name="set_layer", .signature="2u", .types=wlr_layer_shell_unstable_v1_types + 0 },
};

static const struct wl_message zwlr_layer_surface_v1_events[] = {
	{ .name="configure", .signature="uuu", .types=wlr_layer_shell_unstable_v1_types + 0 },
	{ .name="closed", .signature="", .types=wlr_layer_shell_unstable_v1_types + 0 },
};

const struct wl_interface zwlr_layer_surface_v1_interface = {
	.name="zwlr_layer_surface_v1", .version=4,
	.method_count=9, .methods=zwlr_layer_surface_v1_requests,
	.event_count=2, .events=zwlr_layer_surface_v1_events,
};

